
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Tue May 15 07:59:09 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::ASN_Containers_Container_Products;

use Edge::B2B::XML::Type::ASN_Containers_Container_Products_Product;

our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::ASN_Containers_Container_Products->mk_accessors( qw(Product));

Edge::B2B::XML::Type::ASN_Containers_Container_Products->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::ASN_Containers_Container_Products',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'Product' => bless( {
                                                      'class' => 'Edge::B2B::XML::Type::ASN_Containers_Container_Products_Product',
                                                      'documentation' => bless( [
                                                                                  bless( {
                                                                                           'text' => 'Repeating element that contains an individual item'
                                                                                         }, 'XML::Pastor::Schema::Documentation' )
                                                                                ], 'Data::HashArray' ),
                                                      'maxOccurs' => 'unbounded',
                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                      'name' => 'Product',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                      'type' => 'ASN_Containers_Container_Products_Product|http://ws.outdoorindustry.org/v2'
                                                    }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'Product'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'ASN_Containers_Container_Products',
                 'nameIsAutoGenerated' => 1,
                 'scope' => 'local',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::ASN_Containers_Container_Products>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Tue May 15 07:59:09 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<Product>()      - See L<Edge::B2B::XML::Type::ASN_Containers_Container_Products_Product>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
