
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::AttributesExtended;

use Edge::B2B::XML::Type::Attribute;

our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::AttributesExtended->mk_accessors( qw(Attribute));

Edge::B2B::XML::Type::AttributesExtended->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::AttributesExtended',
                 'contentType' => 'complex',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'Optional: This element provides a method for the retailer to include more attributes for the product than just color and size.'
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'elementInfo' => {
                                  'Attribute' => bless( {
                                                        'class' => 'Edge::B2B::XML::Type::Attribute',
                                                        'maxOccurs' => 'unbounded',
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'name' => 'Attribute',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'Attribute|http://ws.outdoorindustry.org/v2'
                                                      }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'Attribute'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'AttributesExtended',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::AttributesExtended>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Optional: This element provides a method for the retailer to include more attributes for the product than just color and size.


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<Attribute>()      - See L<Edge::B2B::XML::Type::Attribute>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
