
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::AvailableToSell;

use Edge::B2B::XML::Type::AttributesExtended;
use Edge::B2B::XML::Type::AvailableToSell_Products;
use Edge::B2B::XML::Type::OIAHeader;

our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::AvailableToSell->mk_accessors( qw(Header Products AttributesExtended));

Edge::B2B::XML::Type::AvailableToSell->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::AvailableToSell',
                 'contentType' => 'complex',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'Document listing product availability by UPC. Reported availability should reflect the current and actual \'ready to ship\' inventory levels and not include restricted/reserved/future inventory.  Rsponse DateTime is the actual date and time when supplied ATS data was recorded. Availability in this document must be current as of this date.'
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'elementInfo' => {
                                  'AttributesExtended' => bless( {
                                                                 'class' => 'Edge::B2B::XML::Type::AttributesExtended',
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'AttributesExtended',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'AttributesExtended|http://ws.outdoorindustry.org/v2'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                  'Header' => bless( {
                                                     'class' => 'Edge::B2B::XML::Type::OIAHeader',
                                                     'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                     'name' => 'Header',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                     'type' => 'OIAHeader|http://ws.outdoorindustry.org/v2'
                                                   }, 'XML::Pastor::Schema::Element' ),
                                  'Products' => bless( {
                                                       'class' => 'Edge::B2B::XML::Type::AvailableToSell_Products',
                                                       'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                       'name' => 'Products',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                       'type' => 'AvailableToSell_Products|http://ws.outdoorindustry.org/v2'
                                                     }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'Header',
                                 'Products',
                                 'AttributesExtended'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'AvailableToSell',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::AvailableToSell>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Document listing product availability by UPC. Reported availability should reflect the current and actual 'ready to ship' inventory levels and not include restricted/reserved/future inventory.  Rsponse DateTime is the actual date and time when supplied ATS data was recorded. Availability in this document must be current as of this date.


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<AttributesExtended>()      - See L<Edge::B2B::XML::Type::AttributesExtended>.

=item B<Header>()      - See L<Edge::B2B::XML::Type::OIAHeader>.

=item B<Products>()      - See L<Edge::B2B::XML::Type::AvailableToSell_Products>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
