
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::BaseTerms;


our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::BaseTerms->mk_accessors( qw(NetDays TermsDescription DueDate));

Edge::B2B::XML::Type::BaseTerms->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::BaseTerms',
                 'contentType' => 'complex',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'Optional. '
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'elementInfo' => {
                                  'DueDate' => bless( {
                                                      'class' => 'XML::Pastor::Builtin::date',
                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'DueDate',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                      'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'NetDays' => bless( {
                                                      'class' => 'XML::Pastor::Builtin::integer',
                                                      'documentation' => bless( [
                                                                                  bless( {
                                                                                           'text' => 'Number of days from the invoice date that the net value of the invoice is due.'
                                                                                         }, 'XML::Pastor::Schema::Documentation' )
                                                                                ], 'Data::HashArray' ),
                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'NetDays',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                      'type' => 'integer|http://www.w3.org/2001/XMLSchema'
                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'TermsDescription' => bless( {
                                                               'class' => 'XML::Pastor::Builtin::token',
                                                               'documentation' => bless( [
                                                                                           bless( {
                                                                                                    'text' => 'Freeform description of the payment terms for this PO'
                                                                                                  }, 'XML::Pastor::Schema::Documentation' )
                                                                                         ], 'Data::HashArray' ),
                                                               'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                               'minOccurs' => '0',
                                                               'name' => 'TermsDescription',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                               'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                             }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'NetDays',
                                 'TermsDescription',
                                 'DueDate'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'BaseTerms',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::BaseTerms>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Optional. 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<DueDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<NetDays>()      - See L<XML::Pastor::Builtin::integer>.

=item B<TermsDescription>()      - See L<XML::Pastor::Builtin::token>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
