
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::BaseCatalog;

use Edge::B2B::XML::Type::AttributesExtended;
use Edge::B2B::XML::Type::BaseCatalog_CatalogDescription;
use Edge::B2B::XML::Type::ID;

our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::BaseCatalog->mk_accessors( qw(CatalogID CatalogDescription CatalogEffectiveDate CatalogEndDate CatalogAvailableToShipDate LastAvailableToShipDate PublicationDate ContractReference ContractDate Comment AttributesExtended));

Edge::B2B::XML::Type::BaseCatalog->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::BaseCatalog',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'AttributesExtended' => bless( {
                                                                 'class' => 'Edge::B2B::XML::Type::AttributesExtended',
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'AttributesExtended',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'AttributesExtended|http://ws.outdoorindustry.org/v2'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                  'CatalogAvailableToShipDate' => bless( {
                                                                         'class' => 'XML::Pastor::Builtin::date',
                                                                         'documentation' => bless( [
                                                                                                     bless( {
                                                                                                              'text' => 'The date the product listed in the catalog will be available to ship.  This date can be overridden by the same field in the product element below.'
                                                                                                            }, 'XML::Pastor::Schema::Documentation' )
                                                                                                   ], 'Data::HashArray' ),
                                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                         'minOccurs' => '0',
                                                                         'name' => 'CatalogAvailableToShipDate',
                                                                         'scope' => 'local',
                                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                         'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'CatalogDescription' => bless( {
                                                                 'class' => 'Edge::B2B::XML::Type::BaseCatalog_CatalogDescription',
                                                                 'documentation' => bless( [
                                                                                             bless( {
                                                                                                      'text' => 'Short description of what the catalog represents. Keep in mind that this field will probably be displayed to an end user. Please in include information that will allow the user to choose one catalog over another.'
                                                                                                    }, 'XML::Pastor::Schema::Documentation' )
                                                                                           ], 'Data::HashArray' ),
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'name' => 'CatalogDescription',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'BaseCatalog_CatalogDescription|http://ws.outdoorindustry.org/v2'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                  'CatalogEffectiveDate' => bless( {
                                                                   'class' => 'XML::Pastor::Builtin::date',
                                                                   'documentation' => bless( [
                                                                                               bless( {
                                                                                                        'text' => 'The date that the retailer can start to order product from this catalog.  This date does not mean the available ship date.  Essentially the vendor systems need to be ready to accept a PO based on this catalog by the CatalogEffectiveDate.  This date must match the date in the CatalogEffectiveDate in the Catalog document itself.'
                                                                                                      }, 'XML::Pastor::Schema::Documentation' )
                                                                                             ], 'Data::HashArray' ),
                                                                   'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                   'name' => 'CatalogEffectiveDate',
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                   'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                                 }, 'XML::Pastor::Schema::Element' ),
                                  'CatalogEndDate' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::date',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Represents the date that the retailer may no longer place a PO with the vendor based on this catalog.  This date must match the date in the CatalogEndDate in the Catalog document itself.'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'name' => 'CatalogEndDate',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'CatalogID' => bless( {
                                                        'class' => 'Edge::B2B::XML::Type::ID',
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'name' => 'CatalogID',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'ID|http://ws.outdoorindustry.org/v2'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'Comment' => bless( {
                                                      'class' => 'XML::Pastor::Builtin::token',
                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'Comment',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                      'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'ContractDate' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::date',
                                                           'documentation' => bless( [
                                                                                       bless( {
                                                                                                'text' => 'If the catalog is based on a particular contractual agreement, the date agreement can be referenced with this field.'
                                                                                              }, 'XML::Pastor::Schema::Documentation' )
                                                                                     ], 'Data::HashArray' ),
                                                           'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'ContractDate',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                           'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'ContractReference' => bless( {
                                                                'class' => 'XML::Pastor::Builtin::token',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'If the catalog is based on a particular contractual agreement, the agreement can be referenced with this field.'
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'ContractReference',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                  'LastAvailableToShipDate' => bless( {
                                                                      'class' => 'XML::Pastor::Builtin::date',
                                                                      'documentation' => bless( [
                                                                                                  bless( {
                                                                                                           'text' => 'The date the product listed in the catalog will no longer be available to be shipped.  This date can be overridden by the same field in the product element below. '
                                                                                                         }, 'XML::Pastor::Schema::Documentation' )
                                                                                                ], 'Data::HashArray' ),
                                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                      'minOccurs' => '0',
                                                                      'name' => 'LastAvailableToShipDate',
                                                                      'scope' => 'local',
                                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                      'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'PublicationDate' => bless( {
                                                              'class' => 'XML::Pastor::Builtin::date',
                                                              'documentation' => bless( [
                                                                                          bless( {
                                                                                                   'text' => 'The date that the catalog was published and made available to retailers or consumers of the catalog.  May be different from the GenerationDate element. '
                                                                                                 }, 'XML::Pastor::Schema::Documentation' )
                                                                                        ], 'Data::HashArray' ),
                                                              'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                              'minOccurs' => '0',
                                                              'name' => 'PublicationDate',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                              'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                            }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'CatalogID',
                                 'CatalogDescription',
                                 'CatalogEffectiveDate',
                                 'CatalogEndDate',
                                 'CatalogAvailableToShipDate',
                                 'LastAvailableToShipDate',
                                 'PublicationDate',
                                 'ContractReference',
                                 'ContractDate',
                                 'Comment',
                                 'AttributesExtended'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'BaseCatalog',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::BaseCatalog>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<AttributesExtended>()      - See L<Edge::B2B::XML::Type::AttributesExtended>.

=item B<CatalogAvailableToShipDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<CatalogDescription>()      - See L<Edge::B2B::XML::Type::BaseCatalog_CatalogDescription>.

=item B<CatalogEffectiveDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<CatalogEndDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<CatalogID>()      - See L<Edge::B2B::XML::Type::ID>.

=item B<Comment>()      - See L<XML::Pastor::Builtin::token>.

=item B<ContractDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ContractReference>()      - See L<XML::Pastor::Builtin::token>.

=item B<LastAvailableToShipDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<PublicationDate>()      - See L<XML::Pastor::Builtin::date>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
