
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::BaseLineItem;

use Edge::B2B::XML::Type::AttributesExtended;
use Edge::B2B::XML::Type::ColorCode;
use Edge::B2B::XML::Type::Gender;
use Edge::B2B::XML::Type::UPC_EAN;

our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::BaseLineItem->mk_accessors( qw(Description UPC_EAN Gender VendorStyleNumber VendorSKU VendorColor VendorColorCode VendorSize BuyerSKU BuyerColor BuyerColorCode BuyerSize UnitOfMeasure AttributesExtended));

Edge::B2B::XML::Type::BaseLineItem->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::BaseLineItem',
                 'contentType' => 'complex',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'Note: If a particular UPC does not appear in this list, the assumption is that it is not available for purchase. Most common reasons for this are: 1) the stock level currently is zero, 2) an incorrect UPC code was supplied in the request, or 3) the supplied UPC code is no longer available for unspecified reasons. The list shows the current inventory levels based on the request and does not in any way indicate recent changes in inventory.
		'
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'elementInfo' => {
                                  'AttributesExtended' => bless( {
                                                                 'class' => 'Edge::B2B::XML::Type::AttributesExtended',
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'AttributesExtended',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'AttributesExtended|http://ws.outdoorindustry.org/v2'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                  'BuyerColor' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::token',
                                                         'documentation' => bless( [
                                                                                     bless( {
                                                                                              'text' => 'Optional. Color assigned to product by the retailer. May be different from VendorColor.'
                                                                                            }, 'XML::Pastor::Schema::Documentation' )
                                                                                   ], 'Data::HashArray' ),
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'BuyerColor',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'BuyerColorCode' => bless( {
                                                             'class' => 'Edge::B2B::XML::Type::ColorCode',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Optional. Buyer assigned color code for the item.'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'BuyerColorCode',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'ColorCode|http://ws.outdoorindustry.org/v2'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'BuyerSKU' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::token',
                                                       'documentation' => bless( [
                                                                                   bless( {
                                                                                            'text' => 'Optional. Buyer assigned Stock Keeping Unit'
                                                                                          }, 'XML::Pastor::Schema::Documentation' )
                                                                                 ], 'Data::HashArray' ),
                                                       'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'BuyerSKU',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                       'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'BuyerSize' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::token',
                                                        'documentation' => bless( [
                                                                                    bless( {
                                                                                             'text' => 'Optional. Size assigned to product by the retailer. May be different from VendorSize.'
                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                  ], 'Data::HashArray' ),
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'BuyerSize',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'Description' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::token',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Describes what the product is. Ex/ Water Bottle'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                          'name' => 'Description',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                          'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'Gender' => bless( {
                                                     'class' => 'Edge::B2B::XML::Type::Gender',
                                                     'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'Gender',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                     'type' => 'Gender|http://ws.outdoorindustry.org/v2'
                                                   }, 'XML::Pastor::Schema::Element' ),
                                  'UPC_EAN' => bless( {
                                                      'class' => 'Edge::B2B::XML::Type::UPC_EAN',
                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                      'name' => 'UPC_EAN',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                      'type' => 'UPC_EAN|http://ws.outdoorindustry.org/v2'
                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'UnitOfMeasure' => bless( {
                                                            'class' => 'XML::Pastor::Builtin::token',
                                                            'documentation' => bless( [
                                                                                        bless( {
                                                                                                 'text' => 'The unit of measure of the product.'
                                                                                               }, 'XML::Pastor::Schema::Documentation' ),
                                                                                        bless( {
                                                                                                 'text' => 'It is highly recommended that this field is consistent. Use EA for each, PR for pair, DZ for dozen. Other units may be used upon coordination between the retailer and vendor'
                                                                                               }, 'XML::Pastor::Schema::Documentation' )
                                                                                      ], 'Data::HashArray' ),
                                                            'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                            'minOccurs' => '0',
                                                            'name' => 'UnitOfMeasure',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                            'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                          }, 'XML::Pastor::Schema::Element' ),
                                  'VendorColor' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::token',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Optional. Vendor assigned color for the item.'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'VendorColor',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                          'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'VendorColorCode' => bless( {
                                                              'class' => 'Edge::B2B::XML::Type::ColorCode',
                                                              'documentation' => bless( [
                                                                                          bless( {
                                                                                                   'text' => 'Optional. Vendor assigned color code for the item.'
                                                                                                 }, 'XML::Pastor::Schema::Documentation' )
                                                                                        ], 'Data::HashArray' ),
                                                              'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                              'minOccurs' => '0',
                                                              'name' => 'VendorColorCode',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                              'type' => 'ColorCode|http://ws.outdoorindustry.org/v2'
                                                            }, 'XML::Pastor::Schema::Element' ),
                                  'VendorSKU' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::token',
                                                        'documentation' => bless( [
                                                                                    bless( {
                                                                                             'text' => 'Optional. Vendor assigned Stock Keeping Unit'
                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                  ], 'Data::HashArray' ),
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'VendorSKU',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'VendorSize' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::token',
                                                         'documentation' => bless( [
                                                                                     bless( {
                                                                                              'text' => 'Optional. Vendor assigned size for the item.'
                                                                                            }, 'XML::Pastor::Schema::Documentation' )
                                                                                   ], 'Data::HashArray' ),
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'VendorSize',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'VendorStyleNumber' => bless( {
                                                                'class' => 'XML::Pastor::Builtin::token',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'Optional. Vendor Style number or identifier. Generally, the style will designate a group of products like a jacket. Allows the grouping of items when there are size runs and/or multiple colors.'
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'VendorStyleNumber',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                              }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'Description',
                                 'UPC_EAN',
                                 'Gender',
                                 'VendorStyleNumber',
                                 'VendorSKU',
                                 'VendorColor',
                                 'VendorColorCode',
                                 'VendorSize',
                                 'BuyerSKU',
                                 'BuyerColor',
                                 'BuyerColorCode',
                                 'BuyerSize',
                                 'UnitOfMeasure',
                                 'AttributesExtended'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'BaseLineItem',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::BaseLineItem>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Note: If a particular UPC does not appear in this list, the assumption is that it is not available for purchase. Most common reasons for this are: 1) the stock level currently is zero, 2) an incorrect UPC code was supplied in the request, or 3) the supplied UPC code is no longer available for unspecified reasons. The list shows the current inventory levels based on the request and does not in any way indicate recent changes in inventory.
		


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<AttributesExtended>()      - See L<Edge::B2B::XML::Type::AttributesExtended>.

=item B<BuyerColor>()      - See L<XML::Pastor::Builtin::token>.

=item B<BuyerColorCode>()      - See L<Edge::B2B::XML::Type::ColorCode>.

=item B<BuyerSKU>()      - See L<XML::Pastor::Builtin::token>.

=item B<BuyerSize>()      - See L<XML::Pastor::Builtin::token>.

=item B<Description>()      - See L<XML::Pastor::Builtin::token>.

=item B<Gender>()      - See L<Edge::B2B::XML::Type::Gender>.

=item B<UPC_EAN>()      - See L<Edge::B2B::XML::Type::UPC_EAN>.

=item B<UnitOfMeasure>()      - See L<XML::Pastor::Builtin::token>.

=item B<VendorColor>()      - See L<XML::Pastor::Builtin::token>.

=item B<VendorColorCode>()      - See L<Edge::B2B::XML::Type::ColorCode>.

=item B<VendorSKU>()      - See L<XML::Pastor::Builtin::token>.

=item B<VendorSize>()      - See L<XML::Pastor::Builtin::token>.

=item B<VendorStyleNumber>()      - See L<XML::Pastor::Builtin::token>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
