
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::BaseDiscount;


our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::BaseDiscount->mk_accessors( qw(DiscountPercent DiscountDays));

Edge::B2B::XML::Type::BaseDiscount->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::BaseDiscount',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'DiscountDays' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::integer',
                                                           'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                           'name' => 'DiscountDays',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                           'type' => 'integer|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'DiscountPercent' => bless( {
                                                              'class' => 'XML::Pastor::Builtin::decimal',
                                                              'documentation' => bless( [
                                                                                          bless( {
                                                                                                   'text' => 'Percent discount of the net invoice to be deducted if invoice is paid DiscountDays (see below) after the invoice date'
                                                                                                 }, 'XML::Pastor::Schema::Documentation' )
                                                                                        ], 'Data::HashArray' ),
                                                              'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                              'name' => 'DiscountPercent',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                              'type' => 'decimal|http://www.w3.org/2001/XMLSchema'
                                                            }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'DiscountPercent',
                                 'DiscountDays'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'BaseDiscount',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::BaseDiscount>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<DiscountDays>()      - See L<XML::Pastor::Builtin::integer>.

=item B<DiscountPercent>()      - See L<XML::Pastor::Builtin::decimal>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
