
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_ImageList_ImageInfo;


our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_ImageList_ImageInfo->mk_accessors( qw(ImageDescription ImageURI));

Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_ImageList_ImageInfo->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_ImageList_ImageInfo',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'ImageDescription' => bless( {
                                                               'class' => 'XML::Pastor::Builtin::token',
                                                               'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                               'name' => 'ImageDescription',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                               'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                             }, 'XML::Pastor::Schema::Element' ),
                                  'ImageURI' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::token',
                                                       'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                       'name' => 'ImageURI',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                       'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'ImageDescription',
                                 'ImageURI'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'Catalog_Products_LineItem_ExtendedInfo_ImageList_ImageInfo',
                 'nameIsAutoGenerated' => 1,
                 'scope' => 'local',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_ImageList_ImageInfo>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<ImageDescription>()      - See L<XML::Pastor::Builtin::token>.

=item B<ImageURI>()      - See L<XML::Pastor::Builtin::token>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
