
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo;

use Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_CrossSellList;
use Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_FeatureList;
use Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_ImageList;
use Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_RGBColor;
use Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_RGBColorSecondary;
use Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_SpecList;

our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo->mk_accessors( qw(LongDescription RGBColor RGBColorDescription RGBColorSecondary RGBColorSecondaryDescription ProductURI PrintReadyImageURI FeatureList SpecList ImageList CrossSellList CategoryLevel1 CategoryLevel2 CategoryLevel3));

Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'CategoryLevel1' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::token',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Optional: The CategoryLevel fields are an attempt to provide a method to separate or categorize products into separate groups.  For instance, separating the tents, sleeping bags and backpacks that are contained in the vendor\'s catalog.  The value of CategoryLevel should be human readable and easily interpreted.  CategoryLevel1 should represent the broadest groupings.  CategoryLevel2 should provide a bit more granularity.  Finally, CategoryLevel3 should provide the most granularity.  CategoryLevel1 should be used first, then 2 and finally 3.  The basic of the categories will can be visualized as a tree structure.  CategoryLevel2 and 3 names/values can repeat across higher level category values.   For example, two CategoryLevel1 values could be \'tents\' and \'sleeping bags\'.  Both the tents and sleeping bags categories could have a \'lightweight\' level 2 category. '
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'CategoryLevel1',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'CategoryLevel2' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::token',
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'CategoryLevel2',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'CategoryLevel3' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::token',
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'CategoryLevel3',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'CrossSellList' => bless( {
                                                            'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_CrossSellList',
                                                            'documentation' => bless( [
                                                                                        bless( {
                                                                                                 'text' => 'Optional: A list of UPC_EAN codes of products that would be a common cross sell for the current product.  This list should be short and only contain products that are relevant.  Ex/ a tent is the current product and the cross sell product is the footprint that matches the tent.'
                                                                                               }, 'XML::Pastor::Schema::Documentation' )
                                                                                      ], 'Data::HashArray' ),
                                                            'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                            'minOccurs' => '0',
                                                            'name' => 'CrossSellList',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                            'type' => 'Catalog_Products_LineItem_ExtendedInfo_CrossSellList|http://ws.outdoorindustry.org/v2'
                                                          }, 'XML::Pastor::Schema::Element' ),
                                  'FeatureList' => bless( {
                                                          'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_FeatureList',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Optional: Unbounded list of product features.  The best example is a bulleted list found on web sites that complements the LongDescription of the product.  '
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'FeatureList',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                          'type' => 'Catalog_Products_LineItem_ExtendedInfo_FeatureList|http://ws.outdoorindustry.org/v2'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'ImageList' => bless( {
                                                        'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_ImageList',
                                                        'documentation' => bless( [
                                                                                    bless( {
                                                                                             'text' => 'Optional: Unbounded list of additional images that are associated with the product.  Might include images of the product from different angles, lifestyle shots or technical drawings. '
                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                  ], 'Data::HashArray' ),
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'ImageList',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'Catalog_Products_LineItem_ExtendedInfo_ImageList|http://ws.outdoorindustry.org/v2'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'LongDescription' => bless( {
                                                              'class' => 'XML::Pastor::Builtin::token',
                                                              'documentation' => bless( [
                                                                                          bless( {
                                                                                                   'text' => 'Optional: Paragraph size description of the product. '
                                                                                                 }, 'XML::Pastor::Schema::Documentation' )
                                                                                        ], 'Data::HashArray' ),
                                                              'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                              'minOccurs' => '0',
                                                              'name' => 'LongDescription',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                              'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                            }, 'XML::Pastor::Schema::Element' ),
                                  'PrintReadyImageURI' => bless( {
                                                                 'class' => 'XML::Pastor::Builtin::token',
                                                                 'documentation' => bless( [
                                                                                             bless( {
                                                                                                      'text' => 'Optional: The URI of a print ready image of the product.  This image should be of high quality and resolution that is appropriate for a full color, glossy ad. '
                                                                                                    }, 'XML::Pastor::Schema::Documentation' )
                                                                                           ], 'Data::HashArray' ),
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'PrintReadyImageURI',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                  'ProductURI' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::token',
                                                         'documentation' => bless( [
                                                                                     bless( {
                                                                                              'text' => 'Optional: the URI of the product on the vendor\'s website.  The intent is to provide a reference for the retailer and/or the consumer that visits the retailer site and clicks through the vendor\'s site.'
                                                                                            }, 'XML::Pastor::Schema::Documentation' )
                                                                                   ], 'Data::HashArray' ),
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'ProductURI',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'RGBColor' => bless( {
                                                       'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_RGBColor',
                                                       'documentation' => bless( [
                                                                                   bless( {
                                                                                            'text' => 'Optional: Standard representation of the basic or primary product color in red, green and blue hexadecimal format.  ex/ #000000 for black, #FFFFFF for white, #FF0000 for red, #00FF00 for green and #0000FF for blue.'
                                                                                          }, 'XML::Pastor::Schema::Documentation' )
                                                                                 ], 'Data::HashArray' ),
                                                       'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'RGBColor',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                       'type' => 'Catalog_Products_LineItem_ExtendedInfo_RGBColor|http://ws.outdoorindustry.org/v2'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'RGBColorDescription' => bless( {
                                                                  'class' => 'XML::Pastor::Builtin::token',
                                                                  'documentation' => bless( [
                                                                                              bless( {
                                                                                                       'text' => 'Optional: Description/name of the color represented by the RGBColor field. '
                                                                                                     }, 'XML::Pastor::Schema::Documentation' )
                                                                                            ], 'Data::HashArray' ),
                                                                  'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                  'minOccurs' => '0',
                                                                  'name' => 'RGBColorDescription',
                                                                  'scope' => 'local',
                                                                  'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                  'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                                }, 'XML::Pastor::Schema::Element' ),
                                  'RGBColorSecondary' => bless( {
                                                                'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_RGBColorSecondary',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'Optional: Standard representation of the secondary product color in red, green and blue hexadecimal format.  ex/ #000000 for black, #FFFFFF for white, #FF0000 for red, #00FF00 for green and #0000FF for blue.'
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'RGBColorSecondary',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'Catalog_Products_LineItem_ExtendedInfo_RGBColorSecondary|http://ws.outdoorindustry.org/v2'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                  'RGBColorSecondaryDescription' => bless( {
                                                                           'class' => 'XML::Pastor::Builtin::token',
                                                                           'documentation' => bless( [
                                                                                                       bless( {
                                                                                                                'text' => 'Optional: Description/name of the color represented by the RGBColorSecondary field. '
                                                                                                              }, 'XML::Pastor::Schema::Documentation' )
                                                                                                     ], 'Data::HashArray' ),
                                                                           'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                           'minOccurs' => '0',
                                                                           'name' => 'RGBColorSecondaryDescription',
                                                                           'scope' => 'local',
                                                                           'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                           'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'SpecList' => bless( {
                                                       'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_SpecList',
                                                       'documentation' => bless( [
                                                                                   bless( {
                                                                                            'text' => 'Optional: Unbounded list of product specifications.  Examples could include, dimensions, weight, strength, etc. '
                                                                                          }, 'XML::Pastor::Schema::Documentation' )
                                                                                 ], 'Data::HashArray' ),
                                                       'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'SpecList',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                       'type' => 'Catalog_Products_LineItem_ExtendedInfo_SpecList|http://ws.outdoorindustry.org/v2'
                                                     }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'LongDescription',
                                 'RGBColor',
                                 'RGBColorDescription',
                                 'RGBColorSecondary',
                                 'RGBColorSecondaryDescription',
                                 'ProductURI',
                                 'PrintReadyImageURI',
                                 'FeatureList',
                                 'SpecList',
                                 'ImageList',
                                 'CrossSellList',
                                 'CategoryLevel1',
                                 'CategoryLevel2',
                                 'CategoryLevel3'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'Catalog_Products_LineItem_ExtendedInfo',
                 'nameIsAutoGenerated' => 1,
                 'scope' => 'local',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<CategoryLevel1>()      - See L<XML::Pastor::Builtin::token>.

=item B<CategoryLevel2>()      - See L<XML::Pastor::Builtin::token>.

=item B<CategoryLevel3>()      - See L<XML::Pastor::Builtin::token>.

=item B<CrossSellList>()      - See L<Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_CrossSellList>.

=item B<FeatureList>()      - See L<Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_FeatureList>.

=item B<ImageList>()      - See L<Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_ImageList>.

=item B<LongDescription>()      - See L<XML::Pastor::Builtin::token>.

=item B<PrintReadyImageURI>()      - See L<XML::Pastor::Builtin::token>.

=item B<ProductURI>()      - See L<XML::Pastor::Builtin::token>.

=item B<RGBColor>()      - See L<Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_RGBColor>.

=item B<RGBColorDescription>()      - See L<XML::Pastor::Builtin::token>.

=item B<RGBColorSecondary>()      - See L<Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_RGBColorSecondary>.

=item B<RGBColorSecondaryDescription>()      - See L<XML::Pastor::Builtin::token>.

=item B<SpecList>()      - See L<Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo_SpecList>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
