
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::Catalog_Products_LineItem;

use Edge::B2B::XML::Type::BaseLineItem;
use Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo;
use Edge::B2B::XML::Type::MonetaryAmount;
use Edge::B2B::XML::Type::UPC_EAN;
use Edge::B2B::XML::Type::Weight;

our @ISA=qw(Edge::B2B::XML::Type::BaseLineItem);

Edge::B2B::XML::Type::Catalog_Products_LineItem->mk_accessors( qw(UnitCost UnitMSRP UnitMAP PackagedWeight ProductWeight ItemEffectiveDate ItemEndDate ItemAvailableToShipDate TradeName BrandName CountryOfOrigin TariffCode MinimumPurchaseQty UPC_EANAvailableForPurchase BaseUnitOfMeasure NumberOfBaseUnits BaseUnitUPC_EAN SellingUPC_EAN ExtendedInfo));

Edge::B2B::XML::Type::Catalog_Products_LineItem->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'base' => 'BaseLineItem|http://ws.outdoorindustry.org/v2',
                 'baseClasses' => [
                                    'Edge::B2B::XML::Type::BaseLineItem'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem',
                 'contentType' => 'complex',
                 'derivedBy' => 'extension',
                 'elementInfo' => {
                                  'BaseUnitOfMeasure' => bless( {
                                                                'class' => 'XML::Pastor::Builtin::token',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'Optional: In the case where an item can be ordered by the case, carton, etc.  This field designates what the lowest common denominator unit of measure is for the product.  For all the UPC/EANs for a given product, this field should contain the same UOM value. '
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'BaseUnitOfMeasure',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                  'BaseUnitUPC_EAN' => bless( {
                                                              'class' => 'Edge::B2B::XML::Type::UPC_EAN',
                                                              'documentation' => bless( [
                                                                                          bless( {
                                                                                                   'text' => 'Optional: In the case where an item can be ordered by the case, carton, etc. This field contains the UPC_EAN code for the base unit product.  '
                                                                                                 }, 'XML::Pastor::Schema::Documentation' )
                                                                                        ], 'Data::HashArray' ),
                                                              'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                              'minOccurs' => '0',
                                                              'name' => 'BaseUnitUPC_EAN',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                              'type' => 'UPC_EAN|http://ws.outdoorindustry.org/v2'
                                                            }, 'XML::Pastor::Schema::Element' ),
                                  'BrandName' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::token',
                                                        'documentation' => bless( [
                                                                                    bless( {
                                                                                             'text' => 'Optional: The brand name of the product.  Typically this brand name will be included on the product packaging.  Some companies manufacture multiple brands and need to be able to show what products belong to a particular brand. '
                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                  ], 'Data::HashArray' ),
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'BrandName',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'CountryOfOrigin' => bless( {
                                                              'class' => 'XML::Pastor::Builtin::token',
                                                              'documentation' => bless( [
                                                                                          bless( {
                                                                                                   'text' => 'Optional: The country of manufacture for the product.  Typically this would be the same as the \'Made in...\' text provided on the labeling or packaging of the product. '
                                                                                                 }, 'XML::Pastor::Schema::Documentation' )
                                                                                        ], 'Data::HashArray' ),
                                                              'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                              'minOccurs' => '0',
                                                              'name' => 'CountryOfOrigin',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                              'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                            }, 'XML::Pastor::Schema::Element' ),
                                  'ExtendedInfo' => bless( {
                                                           'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo',
                                                           'documentation' => bless( [
                                                                                       bless( {
                                                                                                'text' => 'Optional:  This section allows the vendor to supply enhanced information about the product.   This data can be crucial to providing timely and accurate representation of the vendor\'s product in print and online. '
                                                                                              }, 'XML::Pastor::Schema::Documentation' )
                                                                                     ], 'Data::HashArray' ),
                                                           'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'ExtendedInfo',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                           'type' => 'Catalog_Products_LineItem_ExtendedInfo|http://ws.outdoorindustry.org/v2'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                  'ItemAvailableToShipDate' => bless( {
                                                                      'class' => 'XML::Pastor::Builtin::date',
                                                                      'documentation' => bless( [
                                                                                                  bless( {
                                                                                                           'text' => 'Optional: The date the product listed in the catalog will be available to ship.  This field overrides the global value defined in the header position of the catalog.  The intent is to provide a some flexibility, not to have a large discrepancy between the header time frames and the product time frames. '
                                                                                                         }, 'XML::Pastor::Schema::Documentation' )
                                                                                                ], 'Data::HashArray' ),
                                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                      'minOccurs' => '0',
                                                                      'name' => 'ItemAvailableToShipDate',
                                                                      'scope' => 'local',
                                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                      'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'ItemEffectiveDate' => bless( {
                                                                'class' => 'XML::Pastor::Builtin::date',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'Optional: The date that the retailer can start to order product from this catalog.  This date does not mean the available ship date.  Essentially the vendor systems need to be ready to accept a PO based on this catalog by the CatalogEffectiveDate.  This field overrides the global value defined in the header position of the catalog.  The intent is to provide a some flexibility, not to have a large discrepancy between the header time frames and the product time frames. '
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'ItemEffectiveDate',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                  'ItemEndDate' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::date',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Optional: Represents the date that the retailer may no longer place a PO with the vendor for this product.  This field overrides the global value defined in the header position of the catalog.  The intent is to provide a some flexibility, not to have a large discrepancy between the header time frames and the product time frames. '
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'ItemEndDate',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                          'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'MinimumPurchaseQty' => bless( {
                                                                 'class' => 'XML::Pastor::Builtin::integer',
                                                                 'documentation' => bless( [
                                                                                             bless( {
                                                                                                      'text' => 'Optional: The minimum quantity that the retailer needs to but of this product (defined by the UPC_EAN) from the vendor. '
                                                                                                    }, 'XML::Pastor::Schema::Documentation' )
                                                                                           ], 'Data::HashArray' ),
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'MinimumPurchaseQty',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'integer|http://www.w3.org/2001/XMLSchema'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                  'NumberOfBaseUnits' => bless( {
                                                                'class' => 'XML::Pastor::Builtin::integer',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'Optional: In the case where an item can be ordered by the case, carton, etc.  This field contains the number of BaseUnitOfMeasure units are represented by this UPC_EAN.  Ex/ if this UPC_EAN is for a carton that contains 24 energy bars and the energy bar is the base unit, this field should contain the number 24. '
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'NumberOfBaseUnits',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'integer|http://www.w3.org/2001/XMLSchema'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                  'PackagedWeight' => bless( {
                                                             'class' => 'Edge::B2B::XML::Type::Weight',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Optional: The weight of the product in kilograms with all packaging.'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'PackagedWeight',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'Weight|http://ws.outdoorindustry.org/v2'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'ProductWeight' => bless( {
                                                            'class' => 'Edge::B2B::XML::Type::Weight',
                                                            'documentation' => bless( [
                                                                                        bless( {
                                                                                                 'text' => 'Optional: The  weight of the product in kilograms without packaging or in the configuration of its\' intended use by the end user. '
                                                                                               }, 'XML::Pastor::Schema::Documentation' )
                                                                                      ], 'Data::HashArray' ),
                                                            'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                            'minOccurs' => '0',
                                                            'name' => 'ProductWeight',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                            'type' => 'Weight|http://ws.outdoorindustry.org/v2'
                                                          }, 'XML::Pastor::Schema::Element' ),
                                  'SellingUPC_EAN' => bless( {
                                                             'class' => 'Edge::B2B::XML::Type::UPC_EAN',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Optional: If the product represented by UPC_EAN is a \'case\' product that can be sold in smaller UOM\'s.  This field contains the UPC_EAN for the product that can be sold in smaller UOM\'s.  For example, an energy bar is often sold by the box.  The box can have a UPC_EAN code that is different from the individual energy bar packaging.  This field would contain the individual energy bar UPC_EAN if the current product record references the case of energy bars. '
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'SellingUPC_EAN',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'UPC_EAN|http://ws.outdoorindustry.org/v2'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'TariffCode' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::token',
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'TariffCode',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'TradeName' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::token',
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'TradeName',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'UPC_EANAvailableForPurchase' => bless( {
                                                                          'class' => 'XML::Pastor::Builtin::boolean',
                                                                          'documentation' => bless( [
                                                                                                      bless( {
                                                                                                               'text' => 'Optional: This field helps in defining the relationship for an item and its\' case/carton/pallet.  If this product should not be sold, this field should be false.  If it can be sold, the field is true or not present. '
                                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                                    ], 'Data::HashArray' ),
                                                                          'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                          'minOccurs' => '0',
                                                                          'name' => 'UPC_EANAvailableForPurchase',
                                                                          'scope' => 'local',
                                                                          'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                          'type' => 'boolean|http://www.w3.org/2001/XMLSchema'
                                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'UnitCost' => bless( {
                                                       'class' => 'Edge::B2B::XML::Type::MonetaryAmount',
                                                       'documentation' => bless( [
                                                                                   bless( {
                                                                                            'text' => 'The cost of purchasing one unit of the item represented by the UPC_EAN above.'
                                                                                          }, 'XML::Pastor::Schema::Documentation' )
                                                                                 ], 'Data::HashArray' ),
                                                       'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                       'name' => 'UnitCost',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                       'type' => 'MonetaryAmount|http://ws.outdoorindustry.org/v2'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'UnitMAP' => bless( {
                                                      'class' => 'Edge::B2B::XML::Type::MonetaryAmount',
                                                      'documentation' => bless( [
                                                                                  bless( {
                                                                                           'text' => 'Optional: The manufacturer minimum advertised price of the item represented by the UPC_EAN above.'
                                                                                         }, 'XML::Pastor::Schema::Documentation' )
                                                                                ], 'Data::HashArray' ),
                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'UnitMAP',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                      'type' => 'MonetaryAmount|http://ws.outdoorindustry.org/v2'
                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'UnitMSRP' => bless( {
                                                       'class' => 'Edge::B2B::XML::Type::MonetaryAmount',
                                                       'documentation' => bless( [
                                                                                   bless( {
                                                                                            'text' => 'Optional: The manufacturer suggested retail price of the item represented by the UPC_EAN above.'
                                                                                          }, 'XML::Pastor::Schema::Documentation' )
                                                                                 ], 'Data::HashArray' ),
                                                       'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'UnitMSRP',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                       'type' => 'MonetaryAmount|http://ws.outdoorindustry.org/v2'
                                                     }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'UnitCost',
                                 'UnitMSRP',
                                 'UnitMAP',
                                 'PackagedWeight',
                                 'ProductWeight',
                                 'ItemEffectiveDate',
                                 'ItemEndDate',
                                 'ItemAvailableToShipDate',
                                 'TradeName',
                                 'BrandName',
                                 'CountryOfOrigin',
                                 'TariffCode',
                                 'MinimumPurchaseQty',
                                 'UPC_EANAvailableForPurchase',
                                 'BaseUnitOfMeasure',
                                 'NumberOfBaseUnits',
                                 'BaseUnitUPC_EAN',
                                 'SellingUPC_EAN',
                                 'ExtendedInfo'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'Catalog_Products_LineItem',
                 'nameIsAutoGenerated' => 1,
                 'scope' => 'local',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                 'xElementInfo' => {
                                     'AttributesExtended' => bless( {
                                                                    'class' => 'Edge::B2B::XML::Type::AttributesExtended',
                                                                    'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                    'minOccurs' => '0',
                                                                    'name' => 'AttributesExtended',
                                                                    'scope' => 'local',
                                                                    'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                    'type' => 'AttributesExtended|http://ws.outdoorindustry.org/v2'
                                                                  }, 'XML::Pastor::Schema::Element' ),
                                     'BaseUnitOfMeasure' => bless( {
                                                                   'class' => 'XML::Pastor::Builtin::token',
                                                                   'documentation' => bless( [
                                                                                               bless( {
                                                                                                        'text' => 'Optional: In the case where an item can be ordered by the case, carton, etc.  This field designates what the lowest common denominator unit of measure is for the product.  For all the UPC/EANs for a given product, this field should contain the same UOM value. '
                                                                                                      }, 'XML::Pastor::Schema::Documentation' )
                                                                                             ], 'Data::HashArray' ),
                                                                   'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                   'minOccurs' => '0',
                                                                   'name' => 'BaseUnitOfMeasure',
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                   'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                                 }, 'XML::Pastor::Schema::Element' ),
                                     'BaseUnitUPC_EAN' => bless( {
                                                                 'class' => 'Edge::B2B::XML::Type::UPC_EAN',
                                                                 'documentation' => bless( [
                                                                                             bless( {
                                                                                                      'text' => 'Optional: In the case where an item can be ordered by the case, carton, etc. This field contains the UPC_EAN code for the base unit product.  '
                                                                                                    }, 'XML::Pastor::Schema::Documentation' )
                                                                                           ], 'Data::HashArray' ),
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'BaseUnitUPC_EAN',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'UPC_EAN|http://ws.outdoorindustry.org/v2'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                     'BrandName' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::token',
                                                           'documentation' => bless( [
                                                                                       bless( {
                                                                                                'text' => 'Optional: The brand name of the product.  Typically this brand name will be included on the product packaging.  Some companies manufacture multiple brands and need to be able to show what products belong to a particular brand. '
                                                                                              }, 'XML::Pastor::Schema::Documentation' )
                                                                                     ], 'Data::HashArray' ),
                                                           'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'BrandName',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                           'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                     'BuyerColor' => bless( {
                                                            'class' => 'XML::Pastor::Builtin::token',
                                                            'documentation' => bless( [
                                                                                        bless( {
                                                                                                 'text' => 'Optional. Color assigned to product by the retailer. May be different from VendorColor.'
                                                                                               }, 'XML::Pastor::Schema::Documentation' )
                                                                                      ], 'Data::HashArray' ),
                                                            'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                            'minOccurs' => '0',
                                                            'name' => 'BuyerColor',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                            'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                          }, 'XML::Pastor::Schema::Element' ),
                                     'BuyerColorCode' => bless( {
                                                                'class' => 'Edge::B2B::XML::Type::ColorCode',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'Optional. Buyer assigned color code for the item.'
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'BuyerColorCode',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'ColorCode|http://ws.outdoorindustry.org/v2'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                     'BuyerSKU' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::token',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Optional. Buyer assigned Stock Keeping Unit'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'BuyerSKU',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                          'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                     'BuyerSize' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::token',
                                                           'documentation' => bless( [
                                                                                       bless( {
                                                                                                'text' => 'Optional. Size assigned to product by the retailer. May be different from VendorSize.'
                                                                                              }, 'XML::Pastor::Schema::Documentation' )
                                                                                     ], 'Data::HashArray' ),
                                                           'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'BuyerSize',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                           'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                     'CountryOfOrigin' => bless( {
                                                                 'class' => 'XML::Pastor::Builtin::token',
                                                                 'documentation' => bless( [
                                                                                             bless( {
                                                                                                      'text' => 'Optional: The country of manufacture for the product.  Typically this would be the same as the \'Made in...\' text provided on the labeling or packaging of the product. '
                                                                                                    }, 'XML::Pastor::Schema::Documentation' )
                                                                                           ], 'Data::HashArray' ),
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'CountryOfOrigin',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                     'Description' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::token',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Describes what the product is. Ex/ Water Bottle'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'name' => 'Description',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                     'ExtendedInfo' => bless( {
                                                              'class' => 'Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo',
                                                              'documentation' => bless( [
                                                                                          bless( {
                                                                                                   'text' => 'Optional:  This section allows the vendor to supply enhanced information about the product.   This data can be crucial to providing timely and accurate representation of the vendor\'s product in print and online. '
                                                                                                 }, 'XML::Pastor::Schema::Documentation' )
                                                                                        ], 'Data::HashArray' ),
                                                              'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                              'minOccurs' => '0',
                                                              'name' => 'ExtendedInfo',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                              'type' => 'Catalog_Products_LineItem_ExtendedInfo|http://ws.outdoorindustry.org/v2'
                                                            }, 'XML::Pastor::Schema::Element' ),
                                     'Gender' => bless( {
                                                        'class' => 'Edge::B2B::XML::Type::Gender',
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'Gender',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'Gender|http://ws.outdoorindustry.org/v2'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                     'ItemAvailableToShipDate' => bless( {
                                                                         'class' => 'XML::Pastor::Builtin::date',
                                                                         'documentation' => bless( [
                                                                                                     bless( {
                                                                                                              'text' => 'Optional: The date the product listed in the catalog will be available to ship.  This field overrides the global value defined in the header position of the catalog.  The intent is to provide a some flexibility, not to have a large discrepancy between the header time frames and the product time frames. '
                                                                                                            }, 'XML::Pastor::Schema::Documentation' )
                                                                                                   ], 'Data::HashArray' ),
                                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                         'minOccurs' => '0',
                                                                         'name' => 'ItemAvailableToShipDate',
                                                                         'scope' => 'local',
                                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                         'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                                       }, 'XML::Pastor::Schema::Element' ),
                                     'ItemEffectiveDate' => bless( {
                                                                   'class' => 'XML::Pastor::Builtin::date',
                                                                   'documentation' => bless( [
                                                                                               bless( {
                                                                                                        'text' => 'Optional: The date that the retailer can start to order product from this catalog.  This date does not mean the available ship date.  Essentially the vendor systems need to be ready to accept a PO based on this catalog by the CatalogEffectiveDate.  This field overrides the global value defined in the header position of the catalog.  The intent is to provide a some flexibility, not to have a large discrepancy between the header time frames and the product time frames. '
                                                                                                      }, 'XML::Pastor::Schema::Documentation' )
                                                                                             ], 'Data::HashArray' ),
                                                                   'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                   'minOccurs' => '0',
                                                                   'name' => 'ItemEffectiveDate',
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                   'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                                 }, 'XML::Pastor::Schema::Element' ),
                                     'ItemEndDate' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::date',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Optional: Represents the date that the retailer may no longer place a PO with the vendor for this product.  This field overrides the global value defined in the header position of the catalog.  The intent is to provide a some flexibility, not to have a large discrepancy between the header time frames and the product time frames. '
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'ItemEndDate',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                     'MinimumPurchaseQty' => bless( {
                                                                    'class' => 'XML::Pastor::Builtin::integer',
                                                                    'documentation' => bless( [
                                                                                                bless( {
                                                                                                         'text' => 'Optional: The minimum quantity that the retailer needs to but of this product (defined by the UPC_EAN) from the vendor. '
                                                                                                       }, 'XML::Pastor::Schema::Documentation' )
                                                                                              ], 'Data::HashArray' ),
                                                                    'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                    'minOccurs' => '0',
                                                                    'name' => 'MinimumPurchaseQty',
                                                                    'scope' => 'local',
                                                                    'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                    'type' => 'integer|http://www.w3.org/2001/XMLSchema'
                                                                  }, 'XML::Pastor::Schema::Element' ),
                                     'NumberOfBaseUnits' => bless( {
                                                                   'class' => 'XML::Pastor::Builtin::integer',
                                                                   'documentation' => bless( [
                                                                                               bless( {
                                                                                                        'text' => 'Optional: In the case where an item can be ordered by the case, carton, etc.  This field contains the number of BaseUnitOfMeasure units are represented by this UPC_EAN.  Ex/ if this UPC_EAN is for a carton that contains 24 energy bars and the energy bar is the base unit, this field should contain the number 24. '
                                                                                                      }, 'XML::Pastor::Schema::Documentation' )
                                                                                             ], 'Data::HashArray' ),
                                                                   'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                   'minOccurs' => '0',
                                                                   'name' => 'NumberOfBaseUnits',
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                   'type' => 'integer|http://www.w3.org/2001/XMLSchema'
                                                                 }, 'XML::Pastor::Schema::Element' ),
                                     'PackagedWeight' => bless( {
                                                                'class' => 'Edge::B2B::XML::Type::Weight',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'Optional: The weight of the product in kilograms with all packaging.'
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'PackagedWeight',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'Weight|http://ws.outdoorindustry.org/v2'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                     'ProductWeight' => bless( {
                                                               'class' => 'Edge::B2B::XML::Type::Weight',
                                                               'documentation' => bless( [
                                                                                           bless( {
                                                                                                    'text' => 'Optional: The  weight of the product in kilograms without packaging or in the configuration of its\' intended use by the end user. '
                                                                                                  }, 'XML::Pastor::Schema::Documentation' )
                                                                                         ], 'Data::HashArray' ),
                                                               'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                               'minOccurs' => '0',
                                                               'name' => 'ProductWeight',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                               'type' => 'Weight|http://ws.outdoorindustry.org/v2'
                                                             }, 'XML::Pastor::Schema::Element' ),
                                     'SellingUPC_EAN' => bless( {
                                                                'class' => 'Edge::B2B::XML::Type::UPC_EAN',
                                                                'documentation' => bless( [
                                                                                            bless( {
                                                                                                     'text' => 'Optional: If the product represented by UPC_EAN is a \'case\' product that can be sold in smaller UOM\'s.  This field contains the UPC_EAN for the product that can be sold in smaller UOM\'s.  For example, an energy bar is often sold by the box.  The box can have a UPC_EAN code that is different from the individual energy bar packaging.  This field would contain the individual energy bar UPC_EAN if the current product record references the case of energy bars. '
                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                          ], 'Data::HashArray' ),
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'SellingUPC_EAN',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'UPC_EAN|http://ws.outdoorindustry.org/v2'
                                                              }, 'XML::Pastor::Schema::Element' ),
                                     'TariffCode' => bless( {
                                                            'class' => 'XML::Pastor::Builtin::token',
                                                            'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                            'minOccurs' => '0',
                                                            'name' => 'TariffCode',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                            'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                          }, 'XML::Pastor::Schema::Element' ),
                                     'TradeName' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::token',
                                                           'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'TradeName',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                           'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                     'UPC_EAN' => bless( {
                                                         'class' => 'Edge::B2B::XML::Type::UPC_EAN',
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'name' => 'UPC_EAN',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'UPC_EAN|http://ws.outdoorindustry.org/v2'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                     'UPC_EANAvailableForPurchase' => bless( {
                                                                             'class' => 'XML::Pastor::Builtin::boolean',
                                                                             'documentation' => bless( [
                                                                                                         bless( {
                                                                                                                  'text' => 'Optional: This field helps in defining the relationship for an item and its\' case/carton/pallet.  If this product should not be sold, this field should be false.  If it can be sold, the field is true or not present. '
                                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                                       ], 'Data::HashArray' ),
                                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                             'minOccurs' => '0',
                                                                             'name' => 'UPC_EANAvailableForPurchase',
                                                                             'scope' => 'local',
                                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                             'type' => 'boolean|http://www.w3.org/2001/XMLSchema'
                                                                           }, 'XML::Pastor::Schema::Element' ),
                                     'UnitCost' => bless( {
                                                          'class' => 'Edge::B2B::XML::Type::MonetaryAmount',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'The cost of purchasing one unit of the item represented by the UPC_EAN above.'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                          'name' => 'UnitCost',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                          'type' => 'MonetaryAmount|http://ws.outdoorindustry.org/v2'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                     'UnitMAP' => bless( {
                                                         'class' => 'Edge::B2B::XML::Type::MonetaryAmount',
                                                         'documentation' => bless( [
                                                                                     bless( {
                                                                                              'text' => 'Optional: The manufacturer minimum advertised price of the item represented by the UPC_EAN above.'
                                                                                            }, 'XML::Pastor::Schema::Documentation' )
                                                                                   ], 'Data::HashArray' ),
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'UnitMAP',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'MonetaryAmount|http://ws.outdoorindustry.org/v2'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                     'UnitMSRP' => bless( {
                                                          'class' => 'Edge::B2B::XML::Type::MonetaryAmount',
                                                          'documentation' => bless( [
                                                                                      bless( {
                                                                                               'text' => 'Optional: The manufacturer suggested retail price of the item represented by the UPC_EAN above.'
                                                                                             }, 'XML::Pastor::Schema::Documentation' )
                                                                                    ], 'Data::HashArray' ),
                                                          'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'UnitMSRP',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                          'type' => 'MonetaryAmount|http://ws.outdoorindustry.org/v2'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                     'UnitOfMeasure' => bless( {
                                                               'class' => 'XML::Pastor::Builtin::token',
                                                               'documentation' => bless( [
                                                                                           bless( {
                                                                                                    'text' => 'The unit of measure of the product.'
                                                                                                  }, 'XML::Pastor::Schema::Documentation' ),
                                                                                           bless( {
                                                                                                    'text' => 'It is highly recommended that this field is consistent. Use EA for each, PR for pair, DZ for dozen. Other units may be used upon coordination between the retailer and vendor'
                                                                                                  }, 'XML::Pastor::Schema::Documentation' )
                                                                                         ], 'Data::HashArray' ),
                                                               'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                               'minOccurs' => '0',
                                                               'name' => 'UnitOfMeasure',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                               'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                             }, 'XML::Pastor::Schema::Element' ),
                                     'VendorColor' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::token',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'Optional. Vendor assigned color for the item.'
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'VendorColor',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                     'VendorColorCode' => bless( {
                                                                 'class' => 'Edge::B2B::XML::Type::ColorCode',
                                                                 'documentation' => bless( [
                                                                                             bless( {
                                                                                                      'text' => 'Optional. Vendor assigned color code for the item.'
                                                                                                    }, 'XML::Pastor::Schema::Documentation' )
                                                                                           ], 'Data::HashArray' ),
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'VendorColorCode',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'ColorCode|http://ws.outdoorindustry.org/v2'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                     'VendorSKU' => bless( {
                                                           'class' => 'XML::Pastor::Builtin::token',
                                                           'documentation' => bless( [
                                                                                       bless( {
                                                                                                'text' => 'Optional. Vendor assigned Stock Keeping Unit'
                                                                                              }, 'XML::Pastor::Schema::Documentation' )
                                                                                     ], 'Data::HashArray' ),
                                                           'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'VendorSKU',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                           'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                     'VendorSize' => bless( {
                                                            'class' => 'XML::Pastor::Builtin::token',
                                                            'documentation' => bless( [
                                                                                        bless( {
                                                                                                 'text' => 'Optional. Vendor assigned size for the item.'
                                                                                               }, 'XML::Pastor::Schema::Documentation' )
                                                                                      ], 'Data::HashArray' ),
                                                            'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                            'minOccurs' => '0',
                                                            'name' => 'VendorSize',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                            'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                          }, 'XML::Pastor::Schema::Element' ),
                                     'VendorStyleNumber' => bless( {
                                                                   'class' => 'XML::Pastor::Builtin::token',
                                                                   'documentation' => bless( [
                                                                                               bless( {
                                                                                                        'text' => 'Optional. Vendor Style number or identifier. Generally, the style will designate a group of products like a jacket. Allows the grouping of items when there are size runs and/or multiple colors.'
                                                                                                      }, 'XML::Pastor::Schema::Documentation' )
                                                                                             ], 'Data::HashArray' ),
                                                                   'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                   'minOccurs' => '0',
                                                                   'name' => 'VendorStyleNumber',
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                   'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                                 }, 'XML::Pastor::Schema::Element' )
                                   },
                 'xElements' => [
                                  'Description',
                                  'UPC_EAN',
                                  'Gender',
                                  'VendorStyleNumber',
                                  'VendorSKU',
                                  'VendorColor',
                                  'VendorColorCode',
                                  'VendorSize',
                                  'BuyerSKU',
                                  'BuyerColor',
                                  'BuyerColorCode',
                                  'BuyerSize',
                                  'UnitOfMeasure',
                                  'AttributesExtended',
                                  'UnitCost',
                                  'UnitMSRP',
                                  'UnitMAP',
                                  'PackagedWeight',
                                  'ProductWeight',
                                  'ItemEffectiveDate',
                                  'ItemEndDate',
                                  'ItemAvailableToShipDate',
                                  'TradeName',
                                  'BrandName',
                                  'CountryOfOrigin',
                                  'TariffCode',
                                  'MinimumPurchaseQty',
                                  'UPC_EANAvailableForPurchase',
                                  'BaseUnitOfMeasure',
                                  'NumberOfBaseUnits',
                                  'BaseUnitUPC_EAN',
                                  'SellingUPC_EAN',
                                  'ExtendedInfo'
                                ]
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::Catalog_Products_LineItem>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<Edge::B2B::XML::Type::BaseLineItem>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<BaseUnitOfMeasure>()      - See L<XML::Pastor::Builtin::token>.

=item B<BaseUnitUPC_EAN>()      - See L<Edge::B2B::XML::Type::UPC_EAN>.

=item B<BrandName>()      - See L<XML::Pastor::Builtin::token>.

=item B<CountryOfOrigin>()      - See L<XML::Pastor::Builtin::token>.

=item B<ExtendedInfo>()      - See L<Edge::B2B::XML::Type::Catalog_Products_LineItem_ExtendedInfo>.

=item B<ItemAvailableToShipDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ItemEffectiveDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<ItemEndDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<MinimumPurchaseQty>()      - See L<XML::Pastor::Builtin::integer>.

=item B<NumberOfBaseUnits>()      - See L<XML::Pastor::Builtin::integer>.

=item B<PackagedWeight>()      - See L<Edge::B2B::XML::Type::Weight>.

=item B<ProductWeight>()      - See L<Edge::B2B::XML::Type::Weight>.

=item B<SellingUPC_EAN>()      - See L<Edge::B2B::XML::Type::UPC_EAN>.

=item B<TariffCode>()      - See L<XML::Pastor::Builtin::token>.

=item B<TradeName>()      - See L<XML::Pastor::Builtin::token>.

=item B<UPC_EANAvailableForPurchase>()      - See L<XML::Pastor::Builtin::boolean>.

=item B<UnitCost>()      - See L<Edge::B2B::XML::Type::MonetaryAmount>.

=item B<UnitMAP>()      - See L<Edge::B2B::XML::Type::MonetaryAmount>.

=item B<UnitMSRP>()      - See L<Edge::B2B::XML::Type::MonetaryAmount>.

=back


=head1 SEE ALSO

L<Edge::B2B::XML::Type::BaseLineItem>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
