
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::Catalog;

use Edge::B2B::XML::Type::BaseCatalog;
use Edge::B2B::XML::Type::Catalog_Products;
use Edge::B2B::XML::Type::OIAHeader;

our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::Catalog->mk_accessors( qw(Header GenerationDate BaseCatalog Products));

Edge::B2B::XML::Type::Catalog->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::Catalog',
                 'contentType' => 'complex',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'A vendor catalog that lists products for sale, when they are available, pricing, product details, etc.'
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'elementInfo' => {
                                  'BaseCatalog' => bless( {
                                                          'class' => 'Edge::B2B::XML::Type::BaseCatalog',
                                                          'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                          'name' => 'BaseCatalog',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                          'type' => 'BaseCatalog|http://ws.outdoorindustry.org/v2'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'GenerationDate' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::date',
                                                             'documentation' => bless( [
                                                                                         bless( {
                                                                                                  'text' => 'The date that the catalog instance was generated.   If the catalog is generated at run time by a request, this field should the current date. '
                                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                                       ], 'Data::HashArray' ),
                                                             'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                             'name' => 'GenerationDate',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                             'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'Header' => bless( {
                                                     'class' => 'Edge::B2B::XML::Type::OIAHeader',
                                                     'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                     'name' => 'Header',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                     'type' => 'OIAHeader|http://ws.outdoorindustry.org/v2'
                                                   }, 'XML::Pastor::Schema::Element' ),
                                  'Products' => bless( {
                                                       'class' => 'Edge::B2B::XML::Type::Catalog_Products',
                                                       'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                       'name' => 'Products',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                       'type' => 'Catalog_Products|http://ws.outdoorindustry.org/v2'
                                                     }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'Header',
                                 'GenerationDate',
                                 'BaseCatalog',
                                 'Products'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'Catalog',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::Catalog>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

A vendor catalog that lists products for sale, when they are available, pricing, product details, etc.


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<BaseCatalog>()      - See L<Edge::B2B::XML::Type::BaseCatalog>.

=item B<GenerationDate>()      - See L<XML::Pastor::Builtin::date>.

=item B<Header>()      - See L<Edge::B2B::XML::Type::OIAHeader>.

=item B<Products>()      - See L<Edge::B2B::XML::Type::Catalog_Products>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
