
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::ColorCode;


our @ISA=qw(XML::Pastor::Builtin::token);

Edge::B2B::XML::Type::ColorCode->mk_accessors( qw(_ColorCodeType));

# Attribute accessor aliases

sub ColorCodeType { &_ColorCodeType; }

Edge::B2B::XML::Type::ColorCode->XmlSchemaType( bless( {
                 'attributeInfo' => {
                                    'ColorCodeType' => bless( {
                                                              'class' => 'XML::Pastor::Builtin::token',
                                                              'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                              'name' => 'ColorCodeType',
                                                              'scope' => 'local',
                                                              'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                              'type' => 'token|http://www.w3.org/2001/XMLSchema',
                                                              'use' => 'required'
                                                            }, 'XML::Pastor::Schema::Attribute' )
                                  },
                 'attributePrefix' => '_',
                 'attributes' => [
                                   'ColorCodeType'
                                 ],
                 'base' => 'token|http://www.w3.org/2001/XMLSchema',
                 'baseClasses' => [
                                    'XML::Pastor::Builtin::token'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::ColorCode',
                 'contentType' => 'complex',
                 'derivedBy' => 'extension',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'Accomodates a color code and allows for specification of the color code type. Examples: RGB, Pantone, etc.'
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'elementInfo' => {},
                 'elements' => [],
                 'isRedefinable' => 1,
                 'isSimpleContent' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'ColorCode',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::ColorCode>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Accomodates a color code and allows for specification of the color code type. Examples: RGB, Pantone, etc.


=head1 ISA

This class descends from L<XML::Pastor::Builtin::token>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_ColorCodeType>(), B<ColorCodeType>()      - See L<XML::Pastor::Builtin::token>.

=back


=head1 SEE ALSO

L<XML::Pastor::Builtin::token>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
