
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::DocumentReceipt;

use Edge::B2B::XML::Type::AttributesExtended;
use Edge::B2B::XML::Type::DocumentReceipt_DocType;
use Edge::B2B::XML::Type::ID;
use Edge::B2B::XML::Type::OIAHeader;

our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::DocumentReceipt->mk_accessors( qw(Header DocType AcknowledgedDocumentID Comment AttributesExtended));

Edge::B2B::XML::Type::DocumentReceipt->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::DocumentReceipt',
                 'contentType' => 'complex',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'Basic acknowledgement that a document was received and properly parsed.'
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'elementInfo' => {
                                  'AcknowledgedDocumentID' => bless( {
                                                                     'class' => 'Edge::B2B::XML::Type::ID',
                                                                     'documentation' => bless( [
                                                                                                 bless( {
                                                                                                          'text' => 'ID of the original Document which is being receipted by this document.'
                                                                                                        }, 'XML::Pastor::Schema::Documentation' )
                                                                                               ], 'Data::HashArray' ),
                                                                     'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                     'name' => 'AcknowledgedDocumentID',
                                                                     'scope' => 'local',
                                                                     'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                     'type' => 'ID|http://ws.outdoorindustry.org/v2'
                                                                   }, 'XML::Pastor::Schema::Element' ),
                                  'AttributesExtended' => bless( {
                                                                 'class' => 'Edge::B2B::XML::Type::AttributesExtended',
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'AttributesExtended',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'AttributesExtended|http://ws.outdoorindustry.org/v2'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                  'Comment' => bless( {
                                                      'class' => 'XML::Pastor::Builtin::token',
                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'Comment',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                      'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'DocType' => bless( {
                                                      'class' => 'Edge::B2B::XML::Type::DocumentReceipt_DocType',
                                                      'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                      'name' => 'DocType',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                      'type' => 'DocumentReceipt_DocType|http://ws.outdoorindustry.org/v2'
                                                    }, 'XML::Pastor::Schema::Element' ),
                                  'Header' => bless( {
                                                     'class' => 'Edge::B2B::XML::Type::OIAHeader',
                                                     'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                     'name' => 'Header',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                     'type' => 'OIAHeader|http://ws.outdoorindustry.org/v2'
                                                   }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'Header',
                                 'DocType',
                                 'AcknowledgedDocumentID',
                                 'Comment',
                                 'AttributesExtended'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'DocumentReceipt',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::DocumentReceipt>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Basic acknowledgement that a document was received and properly parsed.


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<AcknowledgedDocumentID>()      - See L<Edge::B2B::XML::Type::ID>.

=item B<AttributesExtended>()      - See L<Edge::B2B::XML::Type::AttributesExtended>.

=item B<Comment>()      - See L<XML::Pastor::Builtin::token>.

=item B<DocType>()      - See L<Edge::B2B::XML::Type::DocumentReceipt_DocType>.

=item B<Header>()      - See L<Edge::B2B::XML::Type::OIAHeader>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
