
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::ID;

use Edge::B2B::XML::Type::BaseID;

our @ISA=qw(Edge::B2B::XML::Type::BaseID);

Edge::B2B::XML::Type::ID->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'base' => 'BaseID|http://ws.outdoorindustry.org/v2',
                 'baseClasses' => [
                                    'Edge::B2B::XML::Type::BaseID'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::ID',
                 'contentType' => 'complex',
                 'derivedBy' => 'restriction',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'A globally unique identifier. The ID should never be repeated. GUID\'s work well for this field.'
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'elementInfo' => {},
                 'elements' => [],
                 'isRedefinable' => 1,
                 'isSimpleContent' => 1,
                 'maxLength' => '200',
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'minLength' => '1',
                 'name' => 'ID',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::ID>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

A globally unique identifier. The ID should never be repeated. GUID's work well for this field.


=head1 ISA

This class descends from L<Edge::B2B::XML::Type::BaseID>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 SEE ALSO

L<Edge::B2B::XML::Type::BaseID>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
