
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::MonetaryAmount;

use Edge::B2B::XML::Type::Currency;

our @ISA=qw(XML::Pastor::Builtin::decimal);

Edge::B2B::XML::Type::MonetaryAmount->mk_accessors( qw(_Currency));

# Attribute accessor aliases

sub Currency { &_Currency; }

Edge::B2B::XML::Type::MonetaryAmount->XmlSchemaType( bless( {
                 'attributeInfo' => {
                                    'Currency' => bless( {
                                                         'class' => 'Edge::B2B::XML::Type::Currency',
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'name' => 'Currency',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'Currency|http://ws.outdoorindustry.org/v2',
                                                         'use' => 'required'
                                                       }, 'XML::Pastor::Schema::Attribute' )
                                  },
                 'attributePrefix' => '_',
                 'attributes' => [
                                   'Currency'
                                 ],
                 'base' => 'decimal|http://www.w3.org/2001/XMLSchema',
                 'baseClasses' => [
                                    'XML::Pastor::Builtin::decimal'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::MonetaryAmount',
                 'contentType' => 'complex',
                 'derivedBy' => 'extension',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'Type for money fields - requires currency attribute according to ISO 4217 Currency Abbreviation'
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'elementInfo' => {},
                 'elements' => [],
                 'isRedefinable' => 1,
                 'isSimpleContent' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'MonetaryAmount',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::MonetaryAmount>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Type for money fields - requires currency attribute according to ISO 4217 Currency Abbreviation


=head1 ISA

This class descends from L<XML::Pastor::Builtin::decimal>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_Currency>(), B<Currency>()      - See L<Edge::B2B::XML::Type::Currency>.

=back


=head1 SEE ALSO

L<XML::Pastor::Builtin::decimal>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
