
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::PO_Buyer;


our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::PO_Buyer->mk_accessors( qw(BuyerName BuyerPhone BuyerEMail));

Edge::B2B::XML::Type::PO_Buyer->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::PO_Buyer',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'BuyerEMail' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::token',
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'BuyerEMail',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'BuyerName' => bless( {
                                                        'class' => 'XML::Pastor::Builtin::token',
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'name' => 'BuyerName',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'BuyerPhone' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::token',
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'name' => 'BuyerPhone',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'BuyerName',
                                 'BuyerPhone',
                                 'BuyerEMail'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'PO_Buyer',
                 'nameIsAutoGenerated' => 1,
                 'scope' => 'local',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::PO_Buyer>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<BuyerEMail>()      - See L<XML::Pastor::Builtin::token>.

=item B<BuyerName>()      - See L<XML::Pastor::Builtin::token>.

=item B<BuyerPhone>()      - See L<XML::Pastor::Builtin::token>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
