
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::PO_Transport;

use Edge::B2B::XML::Type::DeliverySpecification;
use Edge::B2B::XML::Type::FOBPoint;
use Edge::B2B::XML::Type::FreightBillingMethod;
use Edge::B2B::XML::Type::ShippingAgent;

our @ISA=qw(XML::Pastor::ComplexType);

Edge::B2B::XML::Type::PO_Transport->mk_accessors( qw(FOBPoint FOBPointOther ShippingAgent ShippingAgentOther DeliverySpecification DeliverySpecificationOther FreightBillingMethod BillToRetailerAccountInfo TransportComments));

Edge::B2B::XML::Type::PO_Transport->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::PO_Transport',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'BillToRetailerAccountInfo' => bless( {
                                                                        'class' => 'XML::Pastor::Builtin::token',
                                                                        'documentation' => bless( [
                                                                                                    bless( {
                                                                                                             'text' => 'Used to provide account information to the vendor about the retailer\'s shipping account. '
                                                                                                           }, 'XML::Pastor::Schema::Documentation' )
                                                                                                  ], 'Data::HashArray' ),
                                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                        'minOccurs' => '0',
                                                                        'name' => 'BillToRetailerAccountInfo',
                                                                        'scope' => 'local',
                                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                        'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'DeliverySpecification' => bless( {
                                                                    'class' => 'Edge::B2B::XML::Type::DeliverySpecification',
                                                                    'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                    'name' => 'DeliverySpecification',
                                                                    'scope' => 'local',
                                                                    'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                    'type' => 'DeliverySpecification|http://ws.outdoorindustry.org/v2'
                                                                  }, 'XML::Pastor::Schema::Element' ),
                                  'DeliverySpecificationOther' => bless( {
                                                                         'class' => 'XML::Pastor::Builtin::token',
                                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                         'minOccurs' => '0',
                                                                         'name' => 'DeliverySpecificationOther',
                                                                         'scope' => 'local',
                                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                         'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                                       }, 'XML::Pastor::Schema::Element' ),
                                  'FOBPoint' => bless( {
                                                       'class' => 'Edge::B2B::XML::Type::FOBPoint',
                                                       'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                       'name' => 'FOBPoint',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                       'type' => 'FOBPoint|http://ws.outdoorindustry.org/v2'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'FOBPointOther' => bless( {
                                                            'class' => 'XML::Pastor::Builtin::token',
                                                            'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                            'minOccurs' => '0',
                                                            'name' => 'FOBPointOther',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                            'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                          }, 'XML::Pastor::Schema::Element' ),
                                  'FreightBillingMethod' => bless( {
                                                                   'class' => 'Edge::B2B::XML::Type::FreightBillingMethod',
                                                                   'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                   'name' => 'FreightBillingMethod',
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                   'type' => 'FreightBillingMethod|http://ws.outdoorindustry.org/v2'
                                                                 }, 'XML::Pastor::Schema::Element' ),
                                  'ShippingAgent' => bless( {
                                                            'class' => 'Edge::B2B::XML::Type::ShippingAgent',
                                                            'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                            'name' => 'ShippingAgent',
                                                            'scope' => 'local',
                                                            'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                            'type' => 'ShippingAgent|http://ws.outdoorindustry.org/v2'
                                                          }, 'XML::Pastor::Schema::Element' ),
                                  'ShippingAgentOther' => bless( {
                                                                 'class' => 'XML::Pastor::Builtin::token',
                                                                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                 'minOccurs' => '0',
                                                                 'name' => 'ShippingAgentOther',
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                 'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                               }, 'XML::Pastor::Schema::Element' ),
                                  'TransportComments' => bless( {
                                                                'class' => 'XML::Pastor::Builtin::token',
                                                                'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                'minOccurs' => '0',
                                                                'name' => 'TransportComments',
                                                                'scope' => 'local',
                                                                'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                              }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'FOBPoint',
                                 'FOBPointOther',
                                 'ShippingAgent',
                                 'ShippingAgentOther',
                                 'DeliverySpecification',
                                 'DeliverySpecificationOther',
                                 'FreightBillingMethod',
                                 'BillToRetailerAccountInfo',
                                 'TransportComments'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'PO_Transport',
                 'nameIsAutoGenerated' => 1,
                 'scope' => 'local',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::PO_Transport>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<BillToRetailerAccountInfo>()      - See L<XML::Pastor::Builtin::token>.

=item B<DeliverySpecification>()      - See L<Edge::B2B::XML::Type::DeliverySpecification>.

=item B<DeliverySpecificationOther>()      - See L<XML::Pastor::Builtin::token>.

=item B<FOBPoint>()      - See L<Edge::B2B::XML::Type::FOBPoint>.

=item B<FOBPointOther>()      - See L<XML::Pastor::Builtin::token>.

=item B<FreightBillingMethod>()      - See L<Edge::B2B::XML::Type::FreightBillingMethod>.

=item B<ShippingAgent>()      - See L<Edge::B2B::XML::Type::ShippingAgent>.

=item B<ShippingAgentOther>()      - See L<XML::Pastor::Builtin::token>.

=item B<TransportComments>()      - See L<XML::Pastor::Builtin::token>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
