
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::PO_Terms;

use Edge::B2B::XML::Type::BaseDiscount;
use Edge::B2B::XML::Type::BaseTerms;

our @ISA=qw(Edge::B2B::XML::Type::BaseTerms);

Edge::B2B::XML::Type::PO_Terms->mk_accessors( qw(Discounts));

Edge::B2B::XML::Type::PO_Terms->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'base' => 'BaseTerms|http://ws.outdoorindustry.org/v2',
                 'baseClasses' => [
                                    'Edge::B2B::XML::Type::BaseTerms'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::PO_Terms',
                 'contentType' => 'complex',
                 'derivedBy' => 'extension',
                 'elementInfo' => {
                                  'Discounts' => bless( {
                                                        'class' => 'Edge::B2B::XML::Type::BaseDiscount',
                                                        'maxOccurs' => 'unbounded',
                                                        'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'Discounts',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                        'type' => 'BaseDiscount|http://ws.outdoorindustry.org/v2'
                                                      }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'Discounts'
                               ],
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'PO_Terms',
                 'nameIsAutoGenerated' => 1,
                 'scope' => 'local',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                 'xElementInfo' => {
                                     'Discounts' => bless( {
                                                           'class' => 'Edge::B2B::XML::Type::BaseDiscount',
                                                           'maxOccurs' => 'unbounded',
                                                           'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'Discounts',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                           'type' => 'BaseDiscount|http://ws.outdoorindustry.org/v2'
                                                         }, 'XML::Pastor::Schema::Element' ),
                                     'DueDate' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::date',
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'DueDate',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'date|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                     'NetDays' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::integer',
                                                         'documentation' => bless( [
                                                                                     bless( {
                                                                                              'text' => 'Number of days from the invoice date that the net value of the invoice is due.'
                                                                                            }, 'XML::Pastor::Schema::Documentation' )
                                                                                   ], 'Data::HashArray' ),
                                                         'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'NetDays',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                         'type' => 'integer|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' ),
                                     'TermsDescription' => bless( {
                                                                  'class' => 'XML::Pastor::Builtin::token',
                                                                  'documentation' => bless( [
                                                                                              bless( {
                                                                                                       'text' => 'Freeform description of the payment terms for this PO'
                                                                                                     }, 'XML::Pastor::Schema::Documentation' )
                                                                                            ], 'Data::HashArray' ),
                                                                  'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                                                                  'minOccurs' => '0',
                                                                  'name' => 'TermsDescription',
                                                                  'scope' => 'local',
                                                                  'targetNamespace' => 'http://ws.outdoorindustry.org/v2',
                                                                  'type' => 'token|http://www.w3.org/2001/XMLSchema'
                                                                }, 'XML::Pastor::Schema::Element' )
                                   },
                 'xElements' => [
                                  'NetDays',
                                  'TermsDescription',
                                  'DueDate',
                                  'Discounts'
                                ]
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::PO_Terms>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<Edge::B2B::XML::Type::BaseTerms>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<Discounts>()      - See L<Edge::B2B::XML::Type::BaseDiscount>.

=back


=head1 SEE ALSO

L<Edge::B2B::XML::Type::BaseTerms>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
