
#PASTOR: Code generated by XML::Pastor/1.0.3 at 'Thu Mar  8 15:06:49 2012'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package Edge::B2B::XML::Type::POType;


our @ISA=qw(XML::Pastor::Builtin::token);

Edge::B2B::XML::Type::POType->XmlSchemaType( bless( {
                 'base' => 'token|http://www.w3.org/2001/XMLSchema',
                 'baseClasses' => [
                                    'XML::Pastor::Builtin::token'
                                  ],
                 'class' => 'Edge::B2B::XML::Type::POType',
                 'contentType' => 'simple',
                 'derivedBy' => 'restriction',
                 'documentation' => bless( [
                                             bless( {
                                                      'text' => 'Indicates what the purpose of this PO is.'
                                                    }, 'XML::Pastor::Schema::Documentation' ),
                                             bless( {
                                                      'text' => '\'Standalone\' is a standard PO (often also referred to as an \'ASAP\' order).'
                                                    }, 'XML::Pastor::Schema::Documentation' ),
                                             bless( {
                                                      'text' => '\'Dropship\' indicates that the PO is to be shipped to an address other than a known retailer address, usually the end  customer.'
                                                    }, 'XML::Pastor::Schema::Documentation' ),
                                             bless( {
                                                      'text' => '\'Preseason\' is a standard preseason order. If intending to \'release\' POs against a master PO at a latter date, use the \'Bulk\' POType
				'
                                                    }, 'XML::Pastor::Schema::Documentation' ),
                                             bless( {
                                                      'text' => '\'EmployeePurchase\' indicates a PO for a retail store employee using a vendor EP purchase plan, usually but not always sent to retailer address
				'
                                                    }, 'XML::Pastor::Schema::Documentation' ),
                                             bless( {
                                                      'text' => '\'ProPurchase\' indicates an order for Pro Purchase, not a retail store employee. More often used internally by vendors. '
                                                    }, 'XML::Pastor::Schema::Documentation' ),
                                             bless( {
                                                      'text' => '\'Bulk\' is similar to Preseason but \'reserves\' product and doesn\'t ship as ordered by quantity or ship date, requires a \'Release\' PO that specifies partial or complete release of the reserved quantities from the original Bulk; more than one \'Release\' event / PO may be allowed against each Bulk'
                                                    }, 'XML::Pastor::Schema::Documentation' ),
                                             bless( {
                                                      'text' => '\'Release\''
                                                    }, 'XML::Pastor::Schema::Documentation' )
                                           ], 'Data::HashArray' ),
                 'enumeration' => {
                                    'Bulk' => 1,
                                    'Dropship' => 1,
                                    'EmployeePurchase' => 1,
                                    'Preseason' => 1,
                                    'ProPurchase' => 1,
                                    'Release' => 1,
                                    'Standalone' => 1
                                  },
                 'isRedefinable' => 1,
                 'metaClass' => 'Edge::B2B::XML::Pastor::Meta',
                 'name' => 'POType',
                 'scope' => 'global',
                 'targetNamespace' => 'http://ws.outdoorindustry.org/v2'
               }, 'XML::Pastor::Schema::SimpleType' ) );

1;


__END__



=head1 NAME

B<Edge::B2B::XML::Type::POType>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Indicates what the purpose of this PO is.

'Standalone' is a standard PO (often also referred to as an 'ASAP' order).

'Dropship' indicates that the PO is to be shipped to an address other than a known retailer address, usually the end  customer.

'Preseason' is a standard preseason order. If intending to 'release' POs against a master PO at a latter date, use the 'Bulk' POType
				

'EmployeePurchase' indicates a PO for a retail store employee using a vendor EP purchase plan, usually but not always sent to retailer address
				

'ProPurchase' indicates an order for Pro Purchase, not a retail store employee. More often used internally by vendors. 

'Bulk' is similar to Preseason but 'reserves' product and doesn't ship as ordered by quantity or ship date, requires a 'Release' PO that specifies partial or complete release of the reserved quantities from the original Bulk; more than one 'Release' event / PO may be allowed against each Bulk

'Release'


=head1 ISA

This class descends from L<XML::Pastor::Builtin::token>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.3 at 'Thu Mar  8 15:06:49 2012'


=head1 SEE ALSO

L<XML::Pastor::Builtin::token>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
